(()=>{'use strict';
if(document.getElementById('a11y-widget-host'))return;
const script=document.currentScript?.src||'',cssUrl=script?new URL('widget.css',script).href:'https://accessibility-widget-psi.vercel.app/widget.css',KEY='empowered_a11y_v3';
const D={lang:'en',open:false,profile:'',fontSize:100,lineHeight:100,letterSpacing:0,fontWeight:false,dyslexia:false,links:false,titles:false,focus:false,guide:false,cursor:false,toc:false,mono:false,lowSat:false,highSat:false,highContrast:false,lightContrast:false,darkContrast:false,animations:false,images:false,tooltips:false};
const EN={title:'Accessibility Menu',profiles:'Accessibility Profiles',content:'Content Adjustments',visual:'Visual & Navigation Aids',color:'Color Adjustments',additional:'Additional Tools',reset:'Reset settings',statement:'Accessibility Statement',close:'Close menu',open:'Open accessibility menu',seizure:'Seizure Safe',screenreader:'Screen Reader Support',vision:'Low Vision',adhd:'ADHD Friendly',cognitive:'Cognitive',motor:'Keyboard Nav',seizureD:'Clears flashes',screenreaderD:'Focus and page navigation',visionD:'Boosts contrast',adhdD:'Reduces noise',cognitiveD:'Reading aids',motorD:'Improves focus',fontSize:'Font Size',lineHeight:'Line Height',letterSpacing:'Letter Spacing',fontWeight:'Font Weight',dyslexia:'Dyslexia Font',links:'Highlight Links',titles:'Highlight Title',focus:'Super Focus',guide:'Reading Guide',cursor:'Big Cursor',toc:'Page Structure',mono:'Monochrome',lowSat:'Low Saturation',highSat:'High Saturation',highContrast:'High Contrast',lightContrast:'Light Contrast',darkContrast:'Dark Contrast',animations:'Stop Animations',images:'Hide Images',tooltips:'Image Tooltips'};
const LANG={
es:{title:'Menú de accesibilidad',profiles:'Perfiles de accesibilidad',content:'Ajustes de contenido',visual:'Ayudas visuales y de navegación',color:'Ajustes de color',additional:'Herramientas adicionales',reset:'Restablecer ajustes',statement:'Declaración de accesibilidad',close:'Cerrar menú',open:'Abrir menú de accesibilidad',seizure:'Seguro para convulsiones',screenreader:'Soporte para lector de pantalla',vision:'Baja visión',adhd:'TDAH',cognitive:'Cognitivo',motor:'Navegación por teclado',fontSize:'Tamaño de fuente',lineHeight:'Altura de línea',letterSpacing:'Espaciado de letras',fontWeight:'Peso de fuente',dyslexia:'Fuente para dislexia',links:'Resaltar enlaces',titles:'Resaltar títulos',focus:'Súper enfoque',guide:'Guía de lectura',cursor:'Cursor grande',toc:'Estructura de página',mono:'Monocromo',lowSat:'Baja saturación',highSat:'Alta saturación',highContrast:'Alto contraste',lightContrast:'Contraste claro',darkContrast:'Contraste oscuro',animations:'Detener animaciones',images:'Ocultar imágenes',tooltips:'Información de imágenes'},
pt:{title:'Menu de acessibilidade',profiles:'Perfis de acessibilidade',content:'Ajustes de conteúdo',visual:'Auxílios visuais e de navegação',color:'Ajustes de cor',additional:'Ferramentas adicionais',reset:'Redefinir configurações',statement:'Declaração de acessibilidade',close:'Fechar menu',open:'Abrir menu de acessibilidade',seizure:'Seguro para convulsões',screenreader:'Suporte para leitor de tela',vision:'Baixa visão',adhd:'TDAH',cognitive:'Cognitivo',motor:'Navegação por teclado',fontSize:'Tamanho da fonte',lineHeight:'Altura da linha',letterSpacing:'Espaçamento de letras',fontWeight:'Peso da fonte',dyslexia:'Fonte para dislexia',links:'Destacar links',titles:'Destacar títulos',focus:'Super foco',guide:'Guia de leitura',cursor:'Cursor grande',toc:'Estrutura da página',mono:'Monocromático',lowSat:'Baixa saturação',highSat:'Alta saturação',highContrast:'Alto contraste',lightContrast:'Contraste claro',darkContrast:'Contraste escuro',animations:'Parar animações',images:'Ocultar imagens',tooltips:'Dicas de imagens'},
fr:{title:"Menu d’accessibilité",profiles:"Profils d’accessibilité",content:'Ajustements du contenu',visual:'Aides visuelles et navigation',color:'Ajustements des couleurs',additional:'Outils supplémentaires',reset:'Réinitialiser',statement:"Déclaration d’accessibilité",close:'Fermer le menu',open:"Ouvrir le menu d’accessibilité",seizure:'Anti-crise',screenreader:"Support du lecteur d’écran",vision:'Malvoyance',adhd:'TDAH',cognitive:'Cognitif',motor:'Navigation clavier',fontSize:'Taille de police',lineHeight:'Hauteur de ligne',letterSpacing:'Espacement des lettres',fontWeight:'Graisse du texte',dyslexia:'Police dyslexie',links:'Surligner les liens',titles:'Surligner les titres',focus:'Super focus',guide:'Guide de lecture',cursor:'Grand curseur',toc:'Structure de page',mono:'Monochrome',lowSat:'Faible saturation',highSat:'Forte saturation',highContrast:'Contraste élevé',lightContrast:'Contraste clair',darkContrast:'Contraste sombre',animations:'Arrêter les animations',images:'Masquer les images',tooltips:'Info-bulles images'},
de:{title:'Barrierefreiheitsmenü',profiles:'Barrierefreiheitsprofile',content:'Inhaltsanpassungen',visual:'Visuelle und Navigationshilfen',color:'Farbanpassungen',additional:'Zusätzliche Werkzeuge',reset:'Einstellungen zurücksetzen',statement:'Erklärung zur Barrierefreiheit',close:'Menü schließen',open:'Barrierefreiheitsmenü öffnen',seizure:'Anfallsicher',screenreader:'Screenreader-Unterstützung',vision:'Sehschwäche',adhd:'ADHS-freundlich',cognitive:'Kognitiv',motor:'Tastaturnavigation',fontSize:'Schriftgröße',lineHeight:'Zeilenhöhe',letterSpacing:'Buchstabenabstand',fontWeight:'Schriftstärke',dyslexia:'Legasthenie-Schrift',links:'Links hervorheben',titles:'Titel hervorheben',focus:'Super-Fokus',guide:'Lesehilfe',cursor:'Großer Mauszeiger',toc:'Seitenstruktur',mono:'Monochrom',lowSat:'Niedrige Sättigung',highSat:'Hohe Sättigung',highContrast:'Hoher Kontrast',lightContrast:'Heller Kontrast',darkContrast:'Dunkler Kontrast',animations:'Animationen stoppen',images:'Bilder ausblenden',tooltips:'Bild-Tooltips'}};
let S=load(),guide,mask,fontRefreshTimer;const tips=new Set(),scaledFonts=new Map();
function load(){try{return{...D,...JSON.parse(localStorage.getItem(KEY)||'{}'),open:false}}catch{return{...D}}}function save(){try{localStorage.setItem(KEY,JSON.stringify({...S,open:false}))}catch{}}
function t(k){return LANG[S.lang]?.[k]||EN[k]||k}const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICONS={
seizure:'<path d="M13 2 4 14h7l-1 8 10-13h-7z"/>',screenreader:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>',vision:'<circle cx="12" cy="12" r="9"/><path d="M12 3v18M3 12h18"/>',adhd:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/>',cognitive:'<path d="M12 6a4 4 0 0 0-7-2v14a4 4 0 0 0 7-2m0-10a4 4 0 0 1 7-2v14a4 4 0 0 1-7-2M8 8h4m4 0h-4"/>',motor:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M6 9h.01M10 9h.01M14 9h.01M18 9h.01M7 14h10"/>',
fontSize:'<path d="M4 5h16M12 5v15M8 20h8"/>',lineHeight:'<path d="M7 5h13M7 12h13M7 19h13M3 5v14M1 7l2-2 2 2M1 17l2 2 2-2"/>',letterSpacing:'<path d="M7 5h10M9 5v12M15 5v12M3 21h18M3 21l3-3M3 21l3 3M21 21l-3-3M21 21l-3 3"/>',fontWeight:'<text x="12" y="18" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" font-weight="800" fill="currentColor" stroke="none">B</text>',dyslexia:'<path d="M5 19 9 5h6l4 14M7 14h10"/><path d="m16 4 4 4"/>',links:'<path d="M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-1 1M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l1-1"/>',titles:'<path d="M4 6h16M4 12h16M4 18h10"/>',focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/>',guide:'<path d="M2 12h20M5 9l-3 3 3 3M19 9l3 3-3 3"/>',cursor:'<path d="M4 3l15 9-7 2-3 7z"/>',toc:'<path d="M7 5h14M7 12h14M7 19h14M3 5h.01M3 12h.01M3 19h.01"/>',
mono:'<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 0 0 18z" fill="currentColor"/>',lowSat:'<circle cx="12" cy="12" r="6"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2"/>',highSat:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3" fill="currentColor"/>',highContrast:'<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 0 0 18z" fill="currentColor"/>',lightContrast:'<circle cx="12" cy="12" r="5"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M19 5l-1.5 1.5M6.5 17.5 5 19"/>',darkContrast:'<path d="M20 15A8 8 0 0 1 9 4a9 9 0 1 0 11 11z"/>',animations:'<circle cx="12" cy="12" r="9"/><path d="M9 8v8M15 8v8"/>',images:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="1.5"/><path d="m4 17 5-5 3 3 2-2 6 6M3 3l18 18"/>',tooltips:'<rect x="3" y="4" width="18" height="14" rx="2"/><path d="M7 9h.01M11 9h6M7 13h10M9 18l3 3 3-3"/>',reset:'<path d="M4 4v6h6M5 9a8 8 0 1 0 1-4"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${ICONS[k]||ICONS.toc}</svg>`,person='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4Zm9 5v2h-6v13h-2v-6h-2v6H9V9H3V7h18Z"/></svg>';
const host=document.body.appendChild(Object.assign(document.createElement('div'),{id:'a11y-widget-host'})),shadow=host.attachShadow({mode:'open'}),link=Object.assign(document.createElement('link'),{rel:'stylesheet',href:cssUrl}),root=Object.assign(document.createElement('div'),{className:'a11y-widget'}),critical=document.createElement('style'),style=document.head.appendChild(Object.assign(document.createElement('style'),{id:'a11y-page-overrides'}));critical.textContent='.a11y-widget{visibility:hidden!important}.a11y-panel,.a11y-launcher{visibility:hidden!important}';link.addEventListener('load',()=>{critical.remove();root.style.visibility='visible'},{once:true});link.addEventListener('error',()=>{console.error('Accessibility widget stylesheet failed to load:',cssUrl)},{once:true});shadow.append(critical,link,root);
const profiles=[['seizure','seizureD'],['screenreader','screenreaderD'],['vision','visionD'],['adhd','adhdD'],['cognitive','cognitiveD'],['motor','motorD']],content=['fontWeight','dyslexia','links','titles'],visual=['guide','cursor','toc'],colors=['mono','lowSat','highSat','highContrast','lightContrast','darkContrast'],extra=['animations','images','tooltips'];
const tool=k=>`<button class="a11y-tool-btn" data-tool="${k}" aria-pressed="${!!S[k]}"><span class="a11y-tool-icon">${icon(k)}</span>${esc(t(k))}</button>`,section=(k,b)=>`<section class="a11y-section"><h3 class="a11y-section-title">${esc(t(k))}</h3>${b}</section>`,step=(k,min,max,n,suffix)=>`<div class="a11y-stepper-row"><div class="a11y-stepper-label">${icon(k)}${esc(t(k))}</div><div class="a11y-stepper-controls"><button class="a11y-stepper-btn" data-step="${k}" data-dir="-1" data-min="${min}" data-max="${max}" data-n="${n}" aria-label="Decrease ${esc(t(k))}">−</button><div class="a11y-stepper-value">${S[k]}${suffix}</div><button class="a11y-stepper-btn" data-step="${k}" data-dir="1" data-min="${min}" data-max="${max}" data-n="${n}" aria-label="Increase ${esc(t(k))}">+</button></div></div>`;
function render(){const old=shadow.querySelector('.a11y-content'),scroll=old?.scrollTop||0;root.innerHTML=`<button class="a11y-launcher" id="launcher" aria-label="${esc(t('open'))}" aria-expanded="${S.open}" aria-controls="panel">${person}</button><div class="a11y-panel${S.open?' is-open':''}" id="panel" role="dialog" aria-modal="true" aria-labelledby="title" aria-hidden="${!S.open}"><header class="a11y-header"><h2 class="a11y-title" id="title">${person}${esc(t('title'))}</h2><div class="a11y-header-actions"><select class="a11y-lang-select" id="lang" aria-label="Language">${['en','es','pt','fr','de'].map(x=>`<option value="${x}"${S.lang===x?' selected':''}>${x.toUpperCase()}</option>`).join('')}</select><button class="a11y-close" id="close" aria-label="${esc(t('close'))}"><svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg></button></div></header><div class="a11y-content">${section('profiles',`<div class="a11y-profile-grid">${profiles.map(([k,d])=>`<button class="a11y-profile-btn" data-profile="${k}" aria-pressed="${S.profile===k}"><span class="a11y-profile-icon">${icon(k)}</span><span class="a11y-profile-text"><span class="a11y-profile-name">${esc(t(k))}</span><span class="a11y-profile-desc">${esc(t(d))}</span></span></button>`).join('')}</div>`)}${section('content',step('fontSize',80,200,10,'%')+step('lineHeight',80,200,10,'%')+step('letterSpacing',0,10,1,'')+`<div class="a11y-tool-grid">${content.map(tool).join('')}</div>`)}${section('visual',`<div class="a11y-tool-grid">${visual.map(tool).join('')}</div><div id="toc-box"></div>`)}${section('color',`<div class="a11y-tool-grid">${colors.map(tool).join('')}</div>`)}${section('additional',`<div class="a11y-tool-grid">${extra.map(tool).join('')}</div>`)}</div><footer class="a11y-footer"><button class="a11y-reset-btn" id="reset">↻ ${esc(t('reset'))}</button><div class="a11y-footer-links"><button class="a11y-statement-link" id="statement-btn" aria-expanded="false">${esc(t('statement'))}</button><span class="a11y-powered-by">Empowered Digital Marketing</span></div><p id="statement" hidden>This widget provides optional display and navigation adjustments. It does not replace assistive technology or guarantee compliance.</p></footer></div>`;bind();shadow.querySelector('.a11y-content').scrollTop=scroll;if(S.toc)buildToc()}
function bind(){const launcher=shadow.getElementById('launcher'),panel=shadow.getElementById('panel');launcher.onclick=()=>open(!S.open);shadow.getElementById('close').onclick=()=>open(false);shadow.getElementById('lang').onchange=e=>{S.lang=e.target.value;save();render();shadow.getElementById('lang').focus()};shadow.getElementById('reset').onclick=reset;shadow.getElementById('statement-btn').onclick=e=>{const p=shadow.getElementById('statement');p.hidden=!p.hidden;e.currentTarget.setAttribute('aria-expanded',!p.hidden)};shadow.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>profile(b.dataset.profile));shadow.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>toggle(b.dataset.tool));shadow.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const k=b.dataset.step;S.profile='';S[k]=Math.max(+b.dataset.min,Math.min(+b.dataset.max,S[k]+(+b.dataset.dir*+b.dataset.n)));save();apply();render()});panel.onkeydown=trap}
function open(v){S.open=v;render();setTimeout(()=>shadow.getElementById(v?'close':'launcher')?.focus(),10)}function trap(e){if(e.key==='Escape'){e.preventDefault();open(false)}if(e.key!=='Tab')return;const a=[...shadow.querySelectorAll('#panel button,#panel select')].filter(x=>x.offsetParent!==null),f=a[0],l=a.at(-1);if(e.shiftKey&&shadow.activeElement===f){e.preventDefault();l.focus()}else if(!e.shiftKey&&shadow.activeElement===l){e.preventDefault();f.focus()}}
function clean(){Object.assign(S,{profile:'',fontSize:100,lineHeight:100,letterSpacing:0,fontWeight:false,dyslexia:false,links:false,titles:false,focus:false,guide:false,cursor:false,toc:false,mono:false,lowSat:false,highSat:false,highContrast:false,lightContrast:false,darkContrast:false,animations:false,images:false,tooltips:false})}
function profile(k){const off=S.profile===k;clean();if(!off){S.profile=k;Object.assign(S,{seizure:{animations:true,lowSat:true},screenreader:{toc:true,links:true,titles:true},vision:{fontSize:120,lineHeight:120,highContrast:true,cursor:true},adhd:{animations:true,guide:true},cognitive:{fontSize:110,lineHeight:130,dyslexia:true,titles:true,guide:true},motor:{cursor:true,animations:true}}[k])}save();apply();render()}
function toggle(k){S.profile='';S[k]=!S[k];const groups=[colors];groups.forEach(g=>{if(S[k]&&g.includes(k))g.filter(x=>x!==k).forEach(x=>S[x]=false)});save();apply();render()}
function reset(){const lang=S.lang;S={...D,lang,open:true};save();apply();render()}
function restoreFontSizes(){
scaledFonts.forEach((original,el)=>{
if(!el||!el.style)return;
if(original.value)el.style.setProperty('font-size',original.value,original.priority);
else el.style.removeProperty('font-size');
});
scaledFonts.clear();
}
function isTextElement(el){
if(!el||el===host||host.contains(el))return false;
if(/^(SCRIPT|STYLE|NOSCRIPT|TEMPLATE|SVG|PATH|META|LINK|BR|HR|IMG|PICTURE|VIDEO|AUDIO|CANVAS|IFRAME)$/.test(el.tagName))return false;
if(el.matches('input,textarea,select,button,option'))return true;
return Array.from(el.childNodes).some(n=>n.nodeType===Node.TEXT_NODE&&n.textContent.trim());
}
function applyFontSize(){
restoreFontSizes();
if(S.fontSize===100)return;
const factor=S.fontSize/100;
const targets=Array.from(document.body.querySelectorAll('*')).filter(isTextElement);
const measurements=targets.map(el=>({el,size:parseFloat(getComputedStyle(el).fontSize)})).filter(x=>Number.isFinite(x.size)&&x.size>0);
measurements.forEach(({el,size})=>{
scaledFonts.set(el,{value:el.style.getPropertyValue('font-size'),priority:el.style.getPropertyPriority('font-size')});
el.style.setProperty('font-size',(size*factor).toFixed(2)+'px','important');
});
}
function scheduleFontRefresh(){
clearTimeout(fontRefreshTimer);
fontRefreshTimer=setTimeout(()=>{if(S.fontSize!==100)applyFontSize()},100);
}
const fontObserver=new MutationObserver(mutations=>{
if(S.fontSize!==100&&mutations.some(m=>Array.from(m.addedNodes).some(n=>n.nodeType===Node.ELEMENT_NODE&&n!==host)))scheduleFontRefresh();
});
fontObserver.observe(document.body,{childList:true,subtree:true});
window.addEventListener('load',scheduleFontRefresh,{once:true});
if(document.fonts&&document.fonts.ready)document.fonts.ready.then(scheduleFontRefresh).catch(()=>{});
function apply(){const q='body *:not(#a11y-widget-host):not(#a11y-widget-host *)';let c='',f=[];applyFontSize();if(S.lineHeight!==100)c+=`${q}{line-height:${(1.5*S.lineHeight/100).toFixed(2)}!important}`;if(S.letterSpacing)c+=`${q}{letter-spacing:${S.letterSpacing}px!important}`;if(S.fontWeight)c+=`${q}{font-weight:700!important}`;if(S.dyslexia)c+=`${q}:not(i):not([class*="icon"]){font-family:OpenDyslexic,"Comic Sans MS",sans-serif!important}`;if(S.links)c+='body a:not(#a11y-widget-host *){outline:3px solid #FD5021!important;outline-offset:2px!important;text-decoration:underline!important}';if(S.titles)c+='body h1,body h2,body h3,body h4,body h5,body h6{outline:3px solid #26B1E8!important;outline-offset:3px!important}';if(S.cursor)c+=`${q}{cursor:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2748%27 height=%2748%27 viewBox=%270 0 48 48%27%3E%3Cpath d=%27M6 4 36 27 23 30 17 43Z%27 fill=%27%23FFFFFF%27 stroke=%27%23173973%27 stroke-width=%274%27 stroke-linejoin=%27round%27/%3E%3C/svg%3E") 6 4,default!important}`;if(S.mono)f.push('grayscale(1)');if(S.lowSat)f.push('saturate(.35)');if(S.highSat)f.push('saturate(1.8)');if(S.highContrast)f.push('contrast(1.5)');if(f.length)c+=`body>*:not(#a11y-widget-host){filter:${f.join(' ')}!important}`;if(S.lightContrast)c+=`body>*:not(#a11y-widget-host),${q}{background:#fff!important;color:#173973!important}`;if(S.darkContrast)c+=`body>*:not(#a11y-widget-host),${q}{background:#173973!important;color:#fff!important}`;if(S.animations)c+='body *:not(#a11y-widget-host),body *:not(#a11y-widget-host)::before,body *:not(#a11y-widget-host)::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}';if(S.images)c+='body img,body video,body picture{visibility:hidden!important}';style.textContent=c;manageEffects()}
function manageEffects(){if(S.guide&&!guide){guide=document.body.appendChild(document.createElement('div'));guide.style.cssText='position:fixed;left:0;right:0;height:4px;background:#FD5021;z-index:999996;pointer-events:none'}if(guide)guide.hidden=!S.guide;if(S.profile==='adhd'&&!mask){mask=document.body.appendChild(document.createElement('div'));mask.style.cssText='position:fixed;left:0;right:0;height:110px;z-index:999995;pointer-events:none;box-shadow:0 -100vh 0 100vh rgba(23,57,115,.62),0 100vh 0 100vh rgba(23,57,115,.62)'}if(mask)mask.hidden=S.profile!=='adhd';if(S.tooltips)document.querySelectorAll('img').forEach(i=>{const x=i.alt||i.getAttribute('aria-label');if(x&&!i.title){i.title=x;i.dataset.a11yTitle='1';tips.add(i)}});else{tips.forEach(i=>{if(i.dataset.a11yTitle){i.removeAttribute('title');delete i.dataset.a11yTitle}});tips.clear()}}
document.addEventListener('pointermove',e=>{if(guide&&S.guide)guide.style.top=e.clientY+'px';if(mask&&S.profile==='adhd')mask.style.top=e.clientY-55+'px'},{passive:true});
function buildToc(){const box=shadow.getElementById('toc-box'),hs=[...document.querySelectorAll('h1,h2,h3,h4,h5,h6')];box.style.cssText='margin-top:10px;padding:10px;border:1px solid #e2e8f0;border-radius:6px;max-height:160px;overflow:auto';if(!hs.length){box.textContent='No headings found.';return}hs.forEach((h,i)=>{const b=document.createElement('button');b.type='button';b.textContent=h.textContent.trim()||h.tagName;b.style.cssText=`display:block;width:100%;padding:5px ${(Number(h.tagName[1])-1)*8}px;border:0;background:transparent;text-align:left;color:#173973;cursor:pointer`;b.onclick=()=>{h.scrollIntoView({behavior:S.animations?'auto':'smooth'});if(!h.hasAttribute('tabindex'))h.tabIndex=-1;h.focus({preventScroll:true})};box.appendChild(b)})}
render();apply();
})();
